{
  "schema_version": "1.6.3",
  "id": "CVE-2021-4041",
  "details": "A flaw was found in ansible-runner. An improper escaping of the shell command, while calling the ansible_runner.interface.run_command, can lead to parameters getting executed as host's shell command. A developer could unintentionally write code that gets executed in the host rather than the virtual environment.",
  "aliases": [],
  "related": [],
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
    }
  ],
  "published": "2022-08-24T16:15:00Z",
  "modified": "2022-08-24T16:15:00Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:22.04:LTS",
        "name": "ansible-runner",
        "purl": "pkg:deb/ubuntu/ansible-runner@2.1.1-1?arch=src?distro=jammy"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.1.1-1"
            }
          ]
        }
      ],
      "versions": [
        "1.4.6-1",
        "1.4.6-1.1"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-ansible-runner-doc": "2.1.1-1",
            "python3-ansible-runner": "2.1.1-1"
          }
        ],
        "availability": "No subscription required",
        "ubuntu_priority": "medium"
      }
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2021-4041"
    },
    {
      "type": "REPORT",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2028074"
    },
    {
      "type": "REPORT",
      "url": "https://www.cve.org/CVERecord?id=CVE-2021-4041"
    }
  ]
}