{
  "id": "USN-4537-1",
  "summary": "aptdaemon vulnerability",
  "details": "Vaisha Bernard discovered that Aptdaemon incorrectly handled the Locale\nproperty. A local attacker could use this issue to test for the presence of\nlocal files.\n",
  "aliases": [],
  "related": [
    "CVE-2020-15703"
  ],
  "published": "2020-09-24T14:52:50.339491Z",
  "modified": "2020-09-24T12:52:50.339491Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:18.04:LTS",
        "name": "aptdaemon"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.1.1+bzr982-0ubuntu19.4"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python3-aptdaemon.gtk3widgets": "1.1.1+bzr982-0ubuntu19.4",
            "python-aptdaemon": "1.1.1+bzr982-0ubuntu19.4",
            "aptdaemon-data": "1.1.1+bzr982-0ubuntu19.4",
            "python3-aptdaemon.test": "1.1.1+bzr982-0ubuntu19.4",
            "aptdaemon": "1.1.1+bzr982-0ubuntu19.4",
            "python-aptdaemon.gtk3widgets": "1.1.1+bzr982-0ubuntu19.4",
            "python3-aptdaemon": "1.1.1+bzr982-0ubuntu19.4"
          }
        ],
        "availability": "No subscription needed"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:20.04:LTS",
        "name": "aptdaemon"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.1.1+bzr982-0ubuntu32.2"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "aptdaemon": "1.1.1+bzr982-0ubuntu32.2",
            "python3-aptdaemon.gtk3widgets": "1.1.1+bzr982-0ubuntu32.2",
            "aptdaemon-data": "1.1.1+bzr982-0ubuntu32.2",
            "python3-aptdaemon.test": "1.1.1+bzr982-0ubuntu32.2",
            "python3-aptdaemon": "1.1.1+bzr982-0ubuntu32.2"
          }
        ],
        "availability": "No subscription needed"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:16.04:LTS",
        "name": "aptdaemon"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.1.1+bzr982-0ubuntu14.4"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python3-aptdaemon.gtk3widgets": "1.1.1+bzr982-0ubuntu14.4",
            "python-aptdaemon": "1.1.1+bzr982-0ubuntu14.4",
            "aptdaemon-data": "1.1.1+bzr982-0ubuntu14.4",
            "python3-aptdaemon.test": "1.1.1+bzr982-0ubuntu14.4",
            "aptdaemon": "1.1.1+bzr982-0ubuntu14.4",
            "python3-aptdaemon.pkcompat": "1.1.1+bzr982-0ubuntu14.4",
            "python-aptdaemon.gtk3widgets": "1.1.1+bzr982-0ubuntu14.4",
            "python3-aptdaemon": "1.1.1+bzr982-0ubuntu14.4"
          }
        ],
        "availability": "No subscription needed"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://ubuntu.com/security/notices/USN-4537-1"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2020-15703"
    }
  ]
}