{
  "id": "USN-6883-1",
  "summary": "glance vulnerability",
  "details": "Martin Kaesberger discovered that Glance incorrectly handled QCOW2 image\nprocessing. An authenticated user could use this issue to access arbitrary\nfiles on the server, possibly exposing sensitive information.\n",
  "aliases": [],
  "related": [
    "CVE-2024-32498"
  ],
  "published": "2024-07-08T11:55:01.004781Z",
  "modified": "2024-07-08T11:55:01.004781Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:20.04:LTS",
        "name": "glance"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2:20.2.0-0ubuntu1.2"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "glance": "2:20.2.0-0ubuntu1.2",
            "glance-api": "2:20.2.0-0ubuntu1.2",
            "glance-common": "2:20.2.0-0ubuntu1.2",
            "python-glance-doc": "2:20.2.0-0ubuntu1.2",
            "python3-glance": "2:20.2.0-0ubuntu1.2"
          }
        ],
        "availability": "No subscription needed"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:22.04:LTS",
        "name": "glance"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2:24.2.1-0ubuntu1.2"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "glance": "2:24.2.1-0ubuntu1.2",
            "glance-api": "2:24.2.1-0ubuntu1.2",
            "glance-common": "2:24.2.1-0ubuntu1.2",
            "python-glance-doc": "2:24.2.1-0ubuntu1.2",
            "python3-glance": "2:24.2.1-0ubuntu1.2"
          }
        ],
        "availability": "No subscription needed"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:23.10",
        "name": "glance"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2:27.0.0-0ubuntu1.2"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "glance": "2:27.0.0-0ubuntu1.2",
            "glance-api": "2:27.0.0-0ubuntu1.2",
            "glance-common": "2:27.0.0-0ubuntu1.2",
            "python-glance-doc": "2:27.0.0-0ubuntu1.2",
            "python3-glance": "2:27.0.0-0ubuntu1.2"
          }
        ],
        "availability": "No subscription needed"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:24.04:LTS",
        "name": "glance"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2:28.0.1-0ubuntu1.2"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "glance": "2:28.0.1-0ubuntu1.2",
            "glance-api": "2:28.0.1-0ubuntu1.2",
            "glance-common": "2:28.0.1-0ubuntu1.2",
            "python-glance-doc": "2:28.0.1-0ubuntu1.2",
            "python3-glance": "2:28.0.1-0ubuntu1.2"
          }
        ],
        "availability": "No subscription needed"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://ubuntu.com/security/notices/USN-6883-1"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2024-32498"
    }
  ]
}