{
  "id": "USN-4420-1",
  "summary": "cinder, python-os-brick vulnerability",
  "details": "David Hill and Eric Harney discovered that Cinder and os-brick incorrectly\nhandled ScaleIO backend credentials. An attacker could possibly use this issue to\nexpose sensitive information.\n",
  "aliases": [],
  "related": [
    "CVE-2020-10755"
  ],
  "published": "2020-07-07T13:51:05.954228Z",
  "modified": "2020-07-07T13:51:05.954228Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:20.04:LTS",
        "name": "cinder"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2:16.1.0-0ubuntu1"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "cinder-backup": "2:16.1.0-0ubuntu1",
            "cinder-api": "2:16.1.0-0ubuntu1",
            "cinder-volume": "2:16.1.0-0ubuntu1",
            "cinder-common": "2:16.1.0-0ubuntu1",
            "python3-cinder": "2:16.1.0-0ubuntu1",
            "cinder-scheduler": "2:16.1.0-0ubuntu1"
          }
        ],
        "availability": "No subscription needed"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:20.04:LTS",
        "name": "python-os-brick"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.0.1-0ubuntu1.2"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "os-brick-common": "3.0.1-0ubuntu1.2",
            "python-os-brick-doc": "3.0.1-0ubuntu1.2",
            "python3-os-brick": "3.0.1-0ubuntu1.2"
          }
        ],
        "availability": "No subscription needed"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:18.04:LTS",
        "name": "cinder"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2:12.0.9-0ubuntu1.2"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-cinder": "2:12.0.9-0ubuntu1.2",
            "cinder-backup": "2:12.0.9-0ubuntu1.2",
            "cinder-api": "2:12.0.9-0ubuntu1.2",
            "cinder-volume": "2:12.0.9-0ubuntu1.2",
            "cinder-common": "2:12.0.9-0ubuntu1.2",
            "cinder-scheduler": "2:12.0.9-0ubuntu1.2"
          }
        ],
        "availability": "No subscription needed"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:18.04:LTS",
        "name": "python-os-brick"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.3.0-0ubuntu1.2"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-os-brick": "2.3.0-0ubuntu1.2",
            "os-brick-common": "2.3.0-0ubuntu1.2",
            "python-os-brick-doc": "2.3.0-0ubuntu1.2",
            "python3-os-brick": "2.3.0-0ubuntu1.2"
          }
        ],
        "availability": "No subscription needed"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://ubuntu.com/security/notices/USN-4420-1"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2020-10755"
    }
  ]
}