{
  "id": "USN-5369-1",
  "summary": "python-oslo.utils vulnerability",
  "details": "It was discovered that oslo.utils incorrectly handled certain inputs.\nAn attacker could possibly use this issue to expose sensitive information.\n",
  "aliases": [],
  "related": [
    "CVE-2022-0718"
  ],
  "published": "2022-04-07T15:30:53.175144Z",
  "modified": "2022-04-07T13:30:53.175144Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:20.04:LTS",
        "name": "python-oslo.utils"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "4.1.1-0ubuntu1.1"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-oslo.utils-doc": "4.1.1-0ubuntu1.1",
            "python3-oslo.utils": "4.1.1-0ubuntu1.1"
          }
        ],
        "availability": "No subscription needed"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:18.04:LTS",
        "name": "python-oslo.utils"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.35.0-0ubuntu1.1"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-oslo.utils": "3.35.0-0ubuntu1.1",
            "python-oslo.utils-doc": "3.35.0-0ubuntu1.1",
            "python3-oslo.utils": "3.35.0-0ubuntu1.1"
          }
        ],
        "availability": "No subscription needed"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:16.04:LTS:Pro",
        "name": "python-oslo.utils"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.8.0-2ubuntu0.1~esm1"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-oslo.utils": "3.8.0-2ubuntu0.1~esm1",
            "python-oslo.utils-doc": "3.8.0-2ubuntu0.1~esm1",
            "python3-oslo.utils": "3.8.0-2ubuntu0.1~esm1",
            "python-oslo-utils": "3.8.0-2ubuntu0.1~esm1",
            "python-oslo-utils-doc": "3.8.0-2ubuntu0.1~esm1",
            "python3-oslo-utils": "3.8.0-2ubuntu0.1~esm1"
          }
        ],
        "availability": "Available with Ubuntu Pro: https://ubuntu.com/pro"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://ubuntu.com/security/notices/USN-5369-1"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2022-0718"
    }
  ]
}