{
  "metadata": {
    "@context": "https://openvex.dev/ns/v0.2.0",
    "@id": "https://github.com/canonical/ubuntu-security-notices/blob/main/vex/cve/2018/CVE-2018-1000808",
    "author": "Canonical Ltd.",
    "timestamp": "2025-01-13T12:13:43.433716",
    "version": 2
  },
  "statements": [
    {
      "vulnerability": {
        "@id": "https://nvd.nist.gov/vuln/detail/CVE-2018-1000808",
        "name": "CVE-2018-1000808",
        "description": "Python Cryptographic Authority pyopenssl version Before 17.5.0 contains a CWE - 401 : Failure to Release Memory Before Removing Last Reference vulnerability in PKCS #12 Store that can result in Denial of service if memory runs low or is exhausted. This attack appear to be exploitable via Depends upon calling application, however it could be as simple as initiating a TLS connection. Anything that would cause the calling application to reload certificates from a PKCS #12 store.. This vulnerability appears to have been fixed in 17.5.0.",
        "aliases": [
          "https://ubuntu.com/security/notices/USN-3813-1",
          "https://www.cve.org/CVERecord?id=CVE-2018-1000808",
          "https://ubuntu.com/security/CVE-2018-1000808"
        ]
      },
      "timestamp": "2018-10-08",
      "products": [
        {
          "@id": "pkg:deb/ubuntu/pyopenssl@0.15.1-2ubuntu0.2?arch=source&distro=xenial"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@0.15.1-2ubuntu0.2?arch=amd64"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@0.15.1-2ubuntu0.2?arch=arm64"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@0.15.1-2ubuntu0.2?arch=armhf"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@0.15.1-2ubuntu0.2?arch=i386"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@0.15.1-2ubuntu0.2?arch=powerpc"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@0.15.1-2ubuntu0.2?arch=ppc64el"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@0.15.1-2ubuntu0.2?arch=s390x"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@0.15.1-2ubuntu0.2?arch=amd64"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@0.15.1-2ubuntu0.2?arch=arm64"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@0.15.1-2ubuntu0.2?arch=armhf"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@0.15.1-2ubuntu0.2?arch=i386"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@0.15.1-2ubuntu0.2?arch=powerpc"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@0.15.1-2ubuntu0.2?arch=ppc64el"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@0.15.1-2ubuntu0.2?arch=s390x"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@0.15.1-2ubuntu0.2?arch=amd64"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@0.15.1-2ubuntu0.2?arch=arm64"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@0.15.1-2ubuntu0.2?arch=armhf"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@0.15.1-2ubuntu0.2?arch=i386"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@0.15.1-2ubuntu0.2?arch=powerpc"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@0.15.1-2ubuntu0.2?arch=ppc64el"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@0.15.1-2ubuntu0.2?arch=s390x"
        }
      ],
      "status": "fixed",
      "status_notes": "This package (for the given release) was vulnerable, but an update has been uploaded and published."
    },
    {
      "vulnerability": {
        "@id": "https://nvd.nist.gov/vuln/detail/CVE-2018-1000808",
        "name": "CVE-2018-1000808",
        "description": "Python Cryptographic Authority pyopenssl version Before 17.5.0 contains a CWE - 401 : Failure to Release Memory Before Removing Last Reference vulnerability in PKCS #12 Store that can result in Denial of service if memory runs low or is exhausted. This attack appear to be exploitable via Depends upon calling application, however it could be as simple as initiating a TLS connection. Anything that would cause the calling application to reload certificates from a PKCS #12 store.. This vulnerability appears to have been fixed in 17.5.0.",
        "aliases": [
          "https://ubuntu.com/security/notices/USN-3813-1",
          "https://www.cve.org/CVERecord?id=CVE-2018-1000808",
          "https://ubuntu.com/security/CVE-2018-1000808"
        ]
      },
      "timestamp": "2018-10-08",
      "products": [
        {
          "@id": "pkg:deb/ubuntu/pyopenssl@0.13-2ubuntu6?arch=source&distro=trusty"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@0.13-2ubuntu6?arch=amd64"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@0.13-2ubuntu6?arch=arm64"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@0.13-2ubuntu6?arch=armhf"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@0.13-2ubuntu6?arch=i386"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@0.13-2ubuntu6?arch=powerpc"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@0.13-2ubuntu6?arch=ppc64el"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-dbg@0.13-2ubuntu6?arch=amd64"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-dbg@0.13-2ubuntu6?arch=arm64"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-dbg@0.13-2ubuntu6?arch=armhf"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-dbg@0.13-2ubuntu6?arch=i386"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-dbg@0.13-2ubuntu6?arch=powerpc"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-dbg@0.13-2ubuntu6?arch=ppc64el"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@0.13-2ubuntu6?arch=amd64"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@0.13-2ubuntu6?arch=arm64"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@0.13-2ubuntu6?arch=armhf"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@0.13-2ubuntu6?arch=i386"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@0.13-2ubuntu6?arch=powerpc"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@0.13-2ubuntu6?arch=ppc64el"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@0.13-2ubuntu6?arch=amd64"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@0.13-2ubuntu6?arch=arm64"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@0.13-2ubuntu6?arch=armhf"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@0.13-2ubuntu6?arch=i386"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@0.13-2ubuntu6?arch=powerpc"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@0.13-2ubuntu6?arch=ppc64el"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl-dbg@0.13-2ubuntu6?arch=amd64"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl-dbg@0.13-2ubuntu6?arch=arm64"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl-dbg@0.13-2ubuntu6?arch=armhf"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl-dbg@0.13-2ubuntu6?arch=i386"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl-dbg@0.13-2ubuntu6?arch=powerpc"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl-dbg@0.13-2ubuntu6?arch=ppc64el"
        },
        {
          "@id": "pkg:deb/ubuntu/pyopenssl@17.5.0-1ubuntu1?arch=source&distro=bionic"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@17.5.0-1ubuntu1?arch=amd64"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@17.5.0-1ubuntu1?arch=arm64"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@17.5.0-1ubuntu1?arch=armhf"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@17.5.0-1ubuntu1?arch=i386"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@17.5.0-1ubuntu1?arch=ppc64el"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl@17.5.0-1ubuntu1?arch=s390x"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@17.5.0-1ubuntu1?arch=amd64"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@17.5.0-1ubuntu1?arch=arm64"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@17.5.0-1ubuntu1?arch=armhf"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@17.5.0-1ubuntu1?arch=i386"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@17.5.0-1ubuntu1?arch=ppc64el"
        },
        {
          "@id": "pkg:deb/ubuntu/python-openssl-doc@17.5.0-1ubuntu1?arch=s390x"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@17.5.0-1ubuntu1?arch=amd64"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@17.5.0-1ubuntu1?arch=arm64"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@17.5.0-1ubuntu1?arch=armhf"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@17.5.0-1ubuntu1?arch=i386"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@17.5.0-1ubuntu1?arch=ppc64el"
        },
        {
          "@id": "pkg:deb/ubuntu/python3-openssl@17.5.0-1ubuntu1?arch=s390x"
        }
      ],
      "status": "not_affected",
      "justification": "vulnerable_code_not_present",
      "impact_statement": "This package (for the given release), while related to the CVE in some way, is not affected by the issue. CVE notes should contain further information, if needed."
    }
  ]
}