{
    "metadata": {
        "@context": "https://openvex.dev/ns/v0.2.0",
        "@id": "https://github.com/canonical/ubuntu-security-notices/blob/main/vex/cve/CVE-2013-6418",
        "author": "Canonical Ltd.",
        "timestamp": "2024-07-31T20:28:18.199497",
        "version": 1
    },
    "statements": [
        {
            "vulnerability": {
                "@id": "https://nvd.nist.gov/vuln/detail/CVE-2013-6418",
                "name": "CVE-2013-6418",
                "description": "PyWBEM 0.7 and earlier uses a separate connection to validate X.509 certificates, which allows man-in-the-middle attackers to spoof a peer via an arbitrary certificate.",
                "aliases": [
                    "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-6418",
                    "http://seclists.org/oss-sec/2013/q4/524",
                    "https://www.cve.org/CVERecord?id=CVE-2013-6418",
                    "https://ubuntu.com/security/CVE-2013-6418"
                ]
            },
            "timestamp": "2014-05-05 17:06:00 UTC",
            "products": [
                {
                    "@id": "pkg:deb/ubuntu/pywbem@0.8.0~dev650-1?arch=src?distro=ubuntu/xenial"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.8.0~dev650-1?arch=amd64"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.8.0~dev650-1?arch=arm64"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.8.0~dev650-1?arch=armhf"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.8.0~dev650-1?arch=i386"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.8.0~dev650-1?arch=powerpc"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.8.0~dev650-1?arch=ppc64el"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.8.0~dev650-1?arch=s390x"
                },
                {
                    "@id": "pkg:deb/ubuntu/pywbem@0.8.0~dev650-1?arch=src?distro=ubuntu/bionic"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.8.0~dev650-1?arch=amd64"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.8.0~dev650-1?arch=arm64"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.8.0~dev650-1?arch=armhf"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.8.0~dev650-1?arch=i386"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.8.0~dev650-1?arch=ppc64el"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.8.0~dev650-1?arch=s390x"
                }
            ],
            "status": "not_affected",
            "justification": "vulnerable_code_not_present",
            "impact_statement": "This package (for the given release), while related to the CVE in some way, is not affected by the issue. CVE notes should contain further information, if needed."
        },
        {
            "vulnerability": {
                "@id": "https://nvd.nist.gov/vuln/detail/CVE-2013-6418",
                "name": "CVE-2013-6418",
                "description": "PyWBEM 0.7 and earlier uses a separate connection to validate X.509 certificates, which allows man-in-the-middle attackers to spoof a peer via an arbitrary certificate.",
                "aliases": [
                    "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2013-6418",
                    "http://seclists.org/oss-sec/2013/q4/524",
                    "https://www.cve.org/CVERecord?id=CVE-2013-6418",
                    "https://ubuntu.com/security/CVE-2013-6418"
                ]
            },
            "timestamp": "2014-05-05 17:06:00 UTC",
            "products": [
                {
                    "@id": "pkg:deb/ubuntu/pywbem@0.7.0-4ubuntu1~14.04.1?arch=src?distro=ubuntu/trusty"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.7.0-4ubuntu1~14.04.1?arch=amd64"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.7.0-4ubuntu1~14.04.1?arch=arm64"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.7.0-4ubuntu1~14.04.1?arch=armhf"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.7.0-4ubuntu1~14.04.1?arch=i386"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.7.0-4ubuntu1~14.04.1?arch=powerpc"
                },
                {
                    "@id": "pkg:deb/ubuntu/python-pywbem@0.7.0-4ubuntu1~14.04.1?arch=ppc64el"
                }
            ],
            "status": "affected",
            "action_statement": "This package (for the given release) is no longer supported. Please upgrade your system."
        }
    ]
}