{
  "schema_version": "1.6.3",
  "id": "CVE-2022-40899",
  "details": "An issue discovered in Python Charmers Future 0.18.2 and earlier allows remote attackers to cause a denial of service via crafted Set-Cookie header from malicious web server.",
  "aliases": [],
  "related": [],
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "published": "2022-12-23T00:15:00Z",
  "modified": "2022-12-23T00:15:00Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:Pro:16.04:LTS",
        "name": "python-future",
        "purl": "pkg:deb/ubuntu/python-future@0.15.2-1ubuntu0.1~esm1?arch=src?distro=esm-apps/xenial"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.15.2-1ubuntu0.1~esm1"
            }
          ]
        }
      ],
      "versions": [
        "0.14.3-1",
        "0.14.3-1build1",
        "0.15.2-1"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-future": "0.15.2-1ubuntu0.1~esm1",
            "python-future-doc": "0.15.2-1ubuntu0.1~esm1",
            "python3-future": "0.15.2-1ubuntu0.1~esm1"
          }
        ],
        "availability": "Available with Ubuntu Pro: https://ubuntu.com/pro",
        "ubuntu_priority": "medium"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:18.04:LTS",
        "name": "python-future",
        "purl": "pkg:deb/ubuntu/python-future@0.15.2-4ubuntu2.1?arch=src?distro=bionic"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.15.2-4ubuntu2.1"
            }
          ]
        }
      ],
      "versions": [
        "0.15.2-4ubuntu1",
        "0.15.2-4ubuntu2"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-future": "0.15.2-4ubuntu2.1",
            "python-future-doc": "0.15.2-4ubuntu2.1",
            "python3-future": "0.15.2-4ubuntu2.1"
          }
        ],
        "availability": "No subscription required",
        "ubuntu_priority": "medium"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:20.04:LTS",
        "name": "python-future",
        "purl": "pkg:deb/ubuntu/python-future@0.18.2-2ubuntu0.1?arch=src?distro=focal"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.18.2-2ubuntu0.1"
            }
          ]
        }
      ],
      "versions": [
        "0.16.0-1",
        "0.18.2-0ubuntu1",
        "0.18.2-1",
        "0.18.2-2"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-future-doc": "0.18.2-2ubuntu0.1",
            "python3-future": "0.18.2-2ubuntu0.1"
          }
        ],
        "availability": "No subscription required",
        "ubuntu_priority": "medium"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:22.04:LTS",
        "name": "python-future",
        "purl": "pkg:deb/ubuntu/python-future@0.18.2-5ubuntu0.1?arch=src?distro=jammy"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.18.2-5ubuntu0.1"
            }
          ]
        }
      ],
      "versions": [
        "0.18.2-5"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-future-doc": "0.18.2-5ubuntu0.1",
            "python3-future": "0.18.2-5ubuntu0.1"
          }
        ],
        "availability": "No subscription required",
        "ubuntu_priority": "medium"
      }
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2022-40899"
    },
    {
      "type": "REPORT",
      "url": "https://pypi.org/project/future/"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/python/cpython/pull/17157"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/PythonCharmers/python-future/blob/master/src/future/backports/http/cookiejar.py#L215"
    },
    {
      "type": "REPORT",
      "url": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/PythonCharmers/python-future/commit/c91d70b34ef0402aef3e9d04364ba98509dca76f"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/notices/USN-5833-1"
    },
    {
      "type": "REPORT",
      "url": "https://www.cve.org/CVERecord?id=CVE-2022-40899"
    }
  ]
}