{
  "schema_version": "1.6.3",
  "id": "CVE-2023-25399",
  "details": "** DISPUTED ** A refcounting issue which leads to potential memory leak was discovered in scipy commit 8627df31ab in Py_FindObjects() function. Note: This is disputed as a bug and not a vulnerability. SciPy is not designed to be exposed to untrusted users or data directly.",
  "aliases": [],
  "related": [],
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "published": "2023-07-06T00:00:00Z",
  "modified": "2024-08-14T04:35:51Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:Pro:20.04:LTS",
        "name": "scipy",
        "purl": "pkg:deb/ubuntu/scipy@1.3.3-3ubuntu0.1~esm1?arch=src?distro=esm-apps/focal"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.3.3-3ubuntu0.1~esm1"
            }
          ]
        }
      ],
      "versions": [
        "1.3.3-3",
        "1.3.3-3build1"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-scipy-doc": "1.3.3-3ubuntu0.1~esm1",
            "python3-scipy": "1.3.3-3ubuntu0.1~esm1",
            "python3-scipy-dbg": "1.3.3-3ubuntu0.1~esm1"
          }
        ],
        "availability": "Available with Ubuntu Pro: https://ubuntu.com/pro",
        "ubuntu_priority": "medium"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:Pro:22.04:LTS",
        "name": "scipy",
        "purl": "pkg:deb/ubuntu/scipy@1.8.0-1exp2ubuntu1+esm1?arch=src?distro=esm-apps/jammy"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.8.0-1exp2ubuntu1+esm1"
            }
          ]
        }
      ],
      "versions": [
        "1.6.0-2",
        "1.7.1-1ubuntu1",
        "1.8.0-1exp2ubuntu1"
      ],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-scipy-doc": "1.8.0-1exp2ubuntu1+esm1",
            "python3-scipy": "1.8.0-1exp2ubuntu1+esm1",
            "python3-scipy-dbgsym": "1.8.0-1exp2ubuntu1+esm1"
          }
        ],
        "availability": "Available with Ubuntu Pro: https://ubuntu.com/pro",
        "ubuntu_priority": "medium"
      }
    },
    {
      "package": {
        "ecosystem": "Ubuntu:24.04:LTS",
        "name": "scipy",
        "purl": "pkg:deb/ubuntu/scipy@1.10.1-2?arch=src?distro=noble"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.10.1-2"
            }
          ]
        }
      ],
      "versions": [],
      "ecosystem_specific": {
        "binaries": [
          {
            "python-scipy-doc": "1.10.1-2",
            "python3-scipy": "1.10.1-2",
            "python3-scipy-dbgsym": "1.10.1-2"
          }
        ],
        "availability": "No subscription required",
        "ubuntu_priority": "medium"
      }
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2023-25399"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/scipy/scipy/issues/16235"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/scipy/scipy/pull/16397"
    },
    {
      "type": "REPORT",
      "url": "http://www.square16.org/achievement/cve-2023-25399/"
    },
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/notices/USN-6226-1"
    },
    {
      "type": "REPORT",
      "url": "https://www.cve.org/CVERecord?id=CVE-2023-25399"
    }
  ]
}