{
  "schema_version": "1.7.0",
  "id": "UBUNTU-CVE-2025-3001",
  "details": "A vulnerability classified as critical was found in PyTorch 2.6.0. This vulnerability affects the function torch.lstm_cell. The manipulation leads to memory corruption. The attack needs to be approached locally. The exploit has been disclosed to the public and may be used.",
  "aliases": [],
  "upstream": [
    "CVE-2025-3001"
  ],
  "related": [],
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L"
    },
    {
      "type": "CVSS_V4",
      "score": "CVSS:4.0/AV:L/AC:L/AT:N/PR:L/UI:N/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N"
    },
    {
      "type": "Ubuntu",
      "score": "medium"
    }
  ],
  "published": "2025-03-31T16:15:00Z",
  "modified": "2025-07-14T04:51:42Z",
  "affected": [
    {
      "package": {
        "ecosystem": "Ubuntu:22.04:LTS",
        "name": "pytorch",
        "purl": "pkg:deb/ubuntu/pytorch@1.8.1-4?arch=source&distro=jammy"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "versions": [
        "1.7.1-7",
        "1.8.1-4"
      ],
      "ecosystem_specific": {}
    },
    {
      "package": {
        "ecosystem": "Ubuntu:25.04",
        "name": "pytorch",
        "purl": "pkg:deb/ubuntu/pytorch@2.6.0+dfsg-5build1?arch=source&distro=plucky"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "versions": [
        "2.4.1-1ubuntu1",
        "2.4.1-1ubuntu3",
        "2.5.1+dfsg-3",
        "2.5.1+dfsg-4build1",
        "2.5.1+dfsg-4build2",
        "2.6.0+dfsg-3",
        "2.6.0+dfsg-4",
        "2.6.0+dfsg-5",
        "2.6.0+dfsg-5build1"
      ],
      "ecosystem_specific": {}
    }
  ],
  "references": [
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2025-3001"
    },
    {
      "type": "REPORT",
      "url": "https://www.cve.org/CVERecord?id=CVE-2025-3001"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/pytorch/pytorch/issues/149626"
    },
    {
      "type": "REPORT",
      "url": "https://github.com/pytorch/pytorch/issues/149626#issue-2935860995"
    },
    {
      "type": "REPORT",
      "url": "https://vuldb.com/?ctiid.302050"
    },
    {
      "type": "REPORT",
      "url": "https://vuldb.com/?id.302050"
    },
    {
      "type": "REPORT",
      "url": "https://vuldb.com/?submit.524212"
    }
  ]
}